#
# Docker compose project used to build docker images
#
# NOTE: Please verify the default environment vars defined in .env file
#
# Usage:
#   build all images:
#     docker-compose -f docker-compose.build.yml build
#   build specific image:
#     docker-compose -f docker-compose.build.yml build [service-name]
#
version: '3'
services:
  oraclexe-domibus:
    build:
      context: oraclexe-domibus
      args:
      - ORACLE_SYS_PASSWORD=changeMe!
      - DOMIBUS_PASSWORD=changeMe!
      - DOMIBUS_DIST_VERSION
      - DOMIBUS_DIST_SHORT_VERSION
    image: oraclexe-domibus:${DOMIBUS_DIST_VERSION}
  edelivery-weblogic-cluster:
    build:
      context: edelivery-weblogic-cluster
      args:
        - USER_ID
        - ENV_ADMIN_PASSWORD=changeMe!
    image: edelivery-weblogic-cluster:12.1.3
  weblogic-cluster-domibus:
    depends_on:
      - oraclexe-domibus
      - edelivery-weblogic-cluster
    build:
      context: weblogic-cluster-domibus
      args:
        - USER_ID
        - ENV_ADMIN_PASSWORD=changeMe!
        - DOMIBUS_PASSWORD=changeMe!
        - DOMIBUS_DIST_VERSION
    image: weblogic-cluster-domibus:${DOMIBUS_DIST_VERSION}
