version: '3'
services:
  oraclexe-domibus:
    build:
      context: oraclexe-domibus
      args:
      - ORACLE_SYS_PASSWORD=changeMe!
      - DOMIBUS_PASSWORD=changeMe!
      - DOMIBUS_DIST_VERSION=3.3
    image: oraclexe-domibus:3.3
  edelivery-weblogic-cluster:
    depends_on:
      - oraclexe-domibus
    build:
      context: edelivery-weblogic-cluster
      args:
        - USER_ID
        - ENV_ADMIN_PASSWORD=changeMe!
    image: edelivery-weblogic-cluster:12.1.3
  weblogic-cluster-domibus:
    depends_on:
      - edelivery-weblogic-cluster
    build:
      context: weblogic-cluster-domibus
      args:
        - USER_ID
        - ENV_ADMIN_PASSWORD=changeMe!
        - DOMIBUS_PASSWORD=changeMe!
    image: weblogic-cluster-domibus:3.3
