#
# Docker compose override project file used to startup the test environment.
# Properties defined here will be merged with the ones from docker-compose.yml file
#
version: '2'
services:
  ##
  ## Corner 2 - Domibus Wildfly MySQL Blue Configuration
  ##
  wildflyc2:
    environment:
      - domibus.msh.pull.cron=0/20 * * * * ?

  ##
  ## Corner 3 - Domibus Tomcat MySQL Red Configuration
  ##
  tomcatc3:
    environment:
      - domibus.msh.pull.cron=0/20 * * * * ?