#C2TomcatMySql-C3TomcatMySqlConfigRed.yml
version: '2'
services:
  mysqlblue:
    image: c7mys7
    container_name: mysql_blue
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    expose:
      - "3306"
    ports:
          - "13306:3306"
  mysqlred:
    image: c7mys7
    container_name: mysql_red
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    expose:
      - "3306"
    ports:
          - "23306:3306"
  domibusblue:
    container_name: domibus_blue
    image: c7-domibus-tomcat:${DOMIBUS_VERSION}
    environment:
      - DB_TYPE=MySQL
      - DB_HOST=mysql_blue
    command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 20s
    depends_on:
      - mysqlblue
    ports:
      - "18081:8080"
  domibusred:
    container_name: domibus_red
    image: c7-domibus-tomcat:${DOMIBUS_VERSION}
    environment:
      - pmodeFile2Upload=/data/domInstall/domibus-gw-sample-pmode-red.xml
      - DB_TYPE=MySQL
      - DB_HOST=mysql_red
    volumes:
      - ../domibus-configs/tomcat/domibus_red/domibus:/data/domibus/domibus/conf/domibus
    command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 20s
    depends_on:
      - mysqlred
    ports:
      - "18082:8080"


