#C2TomcatMySqlConfig1-C3TomcatMySqlConfig2.yml
version: '2'
services:
  mysql1:
    image: c7mys7
    container_name: mysql1
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    expose:
      - "3306"
    ports:
          - "13306:3306"
  mysql2:
    image: c7mys7
    container_name: mysql2
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    expose:
      - "3306"
    ports:
          - "23306:3306"
  domibus1:
    container_name: ap1
    image: c7-domibus-tomcat:${DOMIBUS_VERSION}
    environment:
      - DB_TYPE=MySQL
      - DB_HOST=mysql1
    volumes:
      - ../domibus-configs/tomcat/ap1/domibus:/data/domibus/domibus/conf/domibus
    command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 20s
    depends_on:
      - mysql1
    ports:
      - "18081:8080"
  domibus2:
    container_name: ap2
    image: c7-domibus-tomcat:${DOMIBUS_VERSION}
    environment:
      - DB_TYPE=MySQL
      - DB_HOST=mysql2
    volumes:
      - ../domibus-configs/tomcat/ap2/domibus:/data/domibus/domibus/conf/domibus
    command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 20s
    depends_on:
      - mysql2
    ports:
      - "18082:8080"


