version: '2'
services:
  oracle1:
    container_name: oracle1
    image:  oracle/database:11.2.0.1-xe
    environment:
      - ORACLE_PWD=edelivery
    expose:
      - "1521"
      - "8080"
    ports:
      - "1523:1521"
    shm_size: 1g
  oracle2:
    container_name: oracle2
    image: oracle/database:11.2.0.1-xe
    environment:
      - ORACLE_PWD=edelivery
    expose:
      - "1521"
      - "8080"
    ports:
      - "1522:1521"
    shm_size: 1g
  domibus1:
    container_name: ap1
    image: c7-domibus-tomcat:${DOMIBUS_VERSION}
    environment:
      - DB_TYPE=Oracle
      - DB_HOST=oracle1
      - DB_PORT=1521
      - DB_NAME=/XE
      - DB_USER=edelivery
      - DB_PASS=edelivery
    volumes:
      - ../domibus-configs/tomcat/ap1/domibus:/data/domibus/domibus/conf/domibus
    command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 20s
    ports:
          - "18081:8080"
    depends_on:
      - oracle1
  domibus2:
    container_name: ap2
    image: c7-domibus-tomcat:${DOMIBUS_VERSION}
    environment:
      - DB_TYPE=Oracle
      - DB_HOST=oracle2
      - DB_PORT=1521
      - DB_NAME=/XE
      - DB_USER=edelivery
      - DB_PASS=edelivery
    volumes:
      - ../domibus-configs/tomcat/ap2/domibus:/data/domibus/domibus/conf/domibus
    command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 20s
    ports:
          - "18082:8080"
    depends_on:
      - oracle2
