version: '2'
services:
  mysqlblue:
    container_name: mysql_blue
    image: c7mys7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    expose:
      - "3306"
    ports:
      - "13306:3306"
  oraclered:
    container_name: oraclered
    image: oracle/database:11.2.0.1-xe
    environment:
      - ORACLE_PWD=edelivery
    expose:
      - "1521"
      - "8080"
    ports:
      - "1522:1521"
    shm_size: 1g
  domibusblue:
    container_name: domibus_blue
    image: c7-domibus-wildfly
    environment:
      - DB_TYPE=MySQL
      - DB_HOST=mysql_blue
    command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 20s
    depends_on:
      - mysqlblue
    ports:
      - "18081:8080"
  domibusred:
    container_name: domibus_red
    image: c7-domibus-weblogic
    environment:
      - pmodeFile2Upload=/data/domInstall/domibus-gw-sample-pmode-red.xml
      - PARTY_ID=red
      - DB_TYPE=Oracle
      - DB_HOST=oraclered
      - DB_PORT=1521
      - DB_NAME=/XE
      - DB_USER=edelivery
      - DB_PASS=edelivery
    command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 20s
    ports:
      - "27001:7001"
      - "18082:7003"
    depends_on:
      - oraclered
