version: '2'
services:
  oracleblue:
    container_name: oracle_blue
    image:  oracle/database:11.2.0.1-xe
    environment:
      - ORACLE_PWD=edelivery
    expose:
      - "1521"
      - "8080"
    ports:
      - "11521:1521"
      - "18083:8080"
    shm_size: 1g
  oraclered:
    container_name: oracle_red
    image: oracle/database:11.2.0.1-xe
    environment:
      - ORACLE_PWD=edelivery
    expose:
      - "3306"
      - "8080"
    ports:
      - "21521:1521"
      - "28083:8080"
    shm_size: 1g
  domibusblue:
    container_name: domibus_blue
    image: c7-domibus-wildfly-oracle
    environment:
      - PARTY_ID=blue
      - DB_HOST=oracle_blue
      - DB_PORT=1521
    command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 20s
    ports:
      - "18081:8080"
    depends_on:
      - oracleblue
  domibusred:
    container_name: domibus_red
    image: c7-domibus-wildfly-oracle
    environment:
      - pmodeFile2Upload=/data/domInstall/domibus-gw-sample-pmode-red.xml
      - DB_HOST=oracle_red
      - DB_PORT=1521
    command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 20s
    volumes:
      - ../domibus-configs/wildfly/domibus_red/domibus:/data/domibus/domibus/conf/domibus
    ports:
      - "18082:8080"
    depends_on:
      - oraclered
