version: '2'
services:
  mysqlblue:
    container_name: mysql_blue
    image: c7mys7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    expose:
      - "3306"
    ports:
      - "13306:3306"
  mysqlred:
    container_name: mysql_red
    image: c7mys7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    expose:
      - "3306"
    ports:
      - "23306:3306"
  domibusblue:
    container_name: domibus_blue
    image: c7-domibus-wildfly
    environment:
      - DB_HOST=mysql_blue
      - DB_PORT=3306
    command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 20s
    ports:
      - "18081:8080"
    depends_on:
      - mysqlblue
  domibusred:
    container_name: domibus_red
    image: c7-domibus-wildfly
    environment:
      - pmodeFile2Upload=/data/domInstall/domibus-gw-sample-pmode-red.xml
      - DB_HOST=mysql_red
      - DB_PORT=3306
    volumes:
      - ../domibus-configs/wildfly/domibus_red/domibus:/data/domibus/domibus/conf/domibus
    command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 20s
    ports:
      - "18082:8080"
    depends_on:
      - mysqlred
