version: '3'
services:
  ##
  ## Corner 2 - Domibus Wildfly MySQL Blue Configuration
  ##
  domibusmysqlblue:
    container_name: domibus_mysql_blue
    image: domibus-mysql:${DOMIBUS_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    expose:
      - "3306"
    #ports:
    #  - "33306:3306"
  domibuswildflyblue:
    container_name: domibus_wildfly_blue
    image: domibus-wildfly:${DOMIBUS_VERSION}
    environment:
       - DB_TYPE=MySQL
       - DB_HOST=domibus_mysql_blue
       - DB_PORT=3306
       - DB_USER=edelivery
       - DB_PASS=edelivery
    command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 20s
    #ports:
    #  - "28081:8080"
    depends_on:
      - domibusmysqlblue
  ##
  ## Corner 3 - Domibus Tomcat MySQL Red Configuration
  ##
  domibusmysqlred:
    container_name: domibus_mysql_red
    image: domibus-mysql:${DOMIBUS_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    expose:
      - "3306"
    #ports:
    #      - "23306:3306"
  domibustomcatred:
    container_name: domibus_tomcat_red
    image: domibus-tomcat:${DOMIBUS_VERSION}
    environment:
     - DB_TYPE=MySQL
     - DB_HOST=domibus_mysql_red
     - DB_PORT=3306
     - DB_USER=edelivery
     - DB_PASS=edelivery
     - CERT_ALIAS=red_gw
    volumes:
      - ../domibus-configs/tomcat/domibus_red/domibus:/data/tomcat/conf/domibus
    command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 20s
    depends_on:
      - domibusmysqlred
    #ports:
    #  - "18082:8080"