version: '2'
services:
  wildfly_mysql_blue:
    container_name: wildfly_mysql_blue
    image: domibus-mysql:${DOMIBUS_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    expose:
      - "3306"
    ports:
      - "13306:3306"
  wildfly_mysql_red:
    container_name: wildfly_mysql_red
    image: domibus-mysql:${DOMIBUS_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    expose:
      - "3306"
    ports:
      - "23306:3306"
  wildfly_domibus_blue:
    container_name: wildfly_domibus_blue
    image: domibus-wildfly:${DOMIBUS_VERSION}
    environment:
       - DB_TYPE=MySQL
       - DB_HOST=wildfly_mysql_blue
       - DB_PORT=3306
       - DB_USER=edelivery
       - DB_PASS=edelivery
    command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 20s
    ports:
      - "18083:8080"
    depends_on:
      - wildfly_mysql_blue
  wildfly_domibus_red:
    container_name: wildfly_domibus_red
    image: domibus-wildfly:${DOMIBUS_VERSION}
    environment:
      - DB_TYPE=MySQL
      - DB_HOST=wildfly_mysql_red
      - DB_PORT=3306
      - DB_USER=edelivery
      - DB_PASS=edelivery
    volumes:
      - ../domibus-configs/wildfly/domibus_red/domibus:/data/wildfly/conf/domibus
    command: dockerize -wait tcp://$DB_HOST:$DB_PORT -timeout 20s
    ports:
      - "18084:8080"
    depends_on:
      - wildfly_mysql_red
